window.BINGO_ITEMS = [
  { title: "Zulrah Unique", detail: "Tanz fang, Magic fang, Serp" },
  { title: "Any Justi", detail: "Justi pieces" },
  { title: "Huey Unique", detail: "Wand, earth tome, hides" },
  { title: "Any Ancestral", detail: "Ancestral" },
  { title: "Venator Shard", detail: "Shard" },
  { title: "Any PVM Pet", detail: "No Brutus, Chompy, Chaos ele" },
  { title: "Axe Piece", detail: "Axe piece from any boss" },
  { title: "GWD", detail: "Anything but shards" },
  { title: "Doom", detail: "Eye, Treads, Cloth" },
  { title: "Any Ancient Statuette", detail: "Any ancient statuette" },
  { title: "Nightmare Weapon", detail: "Staff, mace" },
  { title: "Any Masori", detail: "Masori" },
  { title: "CoX Prayer", detail: "Arcane, Dex" },
  { title: "Voidwaker Piece", detail: "Any of the 3 Voidwaker pieces" },
  { title: "Colo Unique", detail: "Any Sunfire, Echo crystal, Ralos" },
  { title: "Moons Unique", detail: "No atlatl darts" },
  { title: "Any Bossing Jar", detail: "Any PVM jar" },
  { title: "Any Inquisitor", detail: "Armour only, no mace" },
  { title: "Royal Titans Crown", detail: "Either crown piece" },
  { title: "Any Virtus Piece", detail: "Virtus robe top, bottom, or mask" },
  { title: "Oathplate Armour Piece", detail: "Lockbox counts but has to show loot tracker" },
  { title: "Corp Sigil", detail: "Any of the 3 sigils" },
  { title: "Any DK Ring", detail: "Ring of life doesn't count" },
  { title: "Nex Weapon", detail: "Nihil Horn or Ancient Hilt; counts for GWD if they want" },
  { title: "Nally Piece", detail: "Any of the 3 Nally pieces" },
  { title: "Wildy Ring", detail: "Any wildy ring" },
  { title: "Any Visage", detail: "Draconic, Skeletal, Wyvern" },
  { title: "Any ToB Weapon", detail: "Sang, Scythe, Rapier" },
  { title: "Gauntlet Seed", detail: "Weapon, enhanced weapon, armour" },
  { title: "Dragon Pickaxe", detail: "Any Dragon pickaxe drop" },
  { title: "Nightmare Orb", detail: "Volatile, Harm, Eldritch" },
  { title: "Barrows", detail: "No bolt racks" },
  { title: "Any Cerb", detail: "Any of the 4" },
  { title: "Zenyte", detail: "Zenyte" },
  { title: "Raids Mega", detail: "Scythe, Tbow, Shadow, Kodai, Elder Maul" },
  { title: "Mutagen", detail: "Magma & Tanz mutagens" },
  { title: "LB/Ward", detail: "Lightbearer or Ward" },
  { title: "TDs Unique", detail: "Synapse or burning claw" },
  { title: "Hydra Unique", detail: "Leather, Ring piece, Claw, Tail" },
  { title: "CoX Weapons", detail: "Weapons + buckler" },
  { title: "Rev Weapons", detail: "Mace, Craws, Scepter" },
  { title: "Soulflame Horn", detail: "Soulflame Horn" },
  { title: "Nex Armour Piece", detail: "Torva piece or Vambs" },
  { title: "Open Slot 44", detail: "Replace this in board.js" },
  { title: "Open Slot 45", detail: "Replace this in board.js" },
  { title: "Open Slot 46", detail: "Replace this in board.js" },
  { title: "Open Slot 47", detail: "Replace this in board.js" },
  { title: "Open Slot 48", detail: "Replace this in board.js" },
  { title: "Open Slot 49", detail: "Replace this in board.js" }
];
